// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"admin/internal/dao"
	"admin/internal/server/http"
	"admin/internal/server/thrift"
	"admin/internal/service"
	"admin/pkg/conf"
	"github.com/kataras/iris"
)

// Injectors from wire.go:

func InitApp() (*iris.Application, func(), error) {
	yaml, err := config()
	if err != nil {
		return nil, nil, err
	}
	thriftThrift, err := thrift.New(yaml)
	if err != nil {
		return nil, nil, err
	}
	db, err := dao.New(yaml)
	if err != nil {
		return nil, nil, err
	}
	daoDao := dao.NewDao(thriftThrift, db)
	serviceService := service.New(daoDao)
	mongo, err := dao.NewMongo(daoDao, yaml)
	if err != nil {
		return nil, nil, err
	}
	application, err := http.New(serviceService, mongo, yaml)
	if err != nil {
		return nil, nil, err
	}
	return application, func() {
	}, nil
}

// wire.go:

func config() (*conf.Yaml, error) {
	return conf.New("configs/conf.yaml")
}
